In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from google.colab import files
upload=files.upload()

Saving heartdisease exp 8.xlsx to heartdisease exp 8 (1).xlsx

In [11]:
df = pd.read_excel('heartdisease exp 8.xlsx')
df.head()

   age  Gender  Family  diet  Lifestyle  cholestrol  heartdisease
0    0       0       1     1          3           0             1
1    0       1       1     1          3           0             1
2    1       0       0     0          2           1             1
3    4       0       1     1          3           2             0
4    3       1       1     0          0           2             0

In [13]:
df.shape

(19, 7)

In [15]:
df.isnull().sum()

age             0
Gender          0
Family          0
diet            0
Lifestyle       0
cholestrol      0
heartdisease    0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           19 non-null     int64
 1   Gender        19 non-null     int64
 2   Family        19 non-null     int64
 3   diet          19 non-null     int64
 4   Lifestyle     19 non-null     int64
 5   cholestrol    19 non-null     int64
 6   heartdisease  19 non-null     int64
dtypes: int64(7)
memory usage: 1.2 KB

In [19]:
df.describe()

,age,Gender,Family,diet,Lifestyle,cholestrol,heartdisease
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,2.157895,0.473684,0.736842,0.578947,1.473684,0.947368,0.578947
std,1.537066,0.512989,0.452414,0.507257,1.306753,0.911268,0.507257
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000
75%,3.500000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000
max,4.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000

In [21]:
df.columns

Index(['age', 'Gender', 'Family', 'diet', 'Lifestyle', 'cholestrol',
       'heartdisease'],
      dtype='object')

In [23]:
!pip install pgmpy==1.0.0
import pgmpy
print(pgmpy.__version__)

Requirement already satisfied: pgmpy==1.0.0 in /usr/local/lib/python3.13/dist-packages (1.0.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.5.3)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Requirement already satisfied: pyro-api>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.3.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
1.0.0

In [25]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
model = DiscreteBayesianNetwork([
('age', 'heartdisease'),
('Gender', 'heartdisease'),
('Family', 'heartdisease'),
('diet', 'heartdisease'),
('Lifestyle', 'heartdisease'),
('cholestrol', 'heartdisease') ])
mle = MaximumLikelihoodEstimator(model, df)
cpds = mle.get_parameters()
model.add_cpds(*cpds)
print(model.get_cpds('heartdisease'))

+-----------------+---------------+-----+---------------+---------------+
| Family          | Family(0)     | ... | Family(1)     | Family(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Gender          | Gender(0)     | ... | Gender(1)     | Gender(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Lifestyle       | Lifestyle(0)  | ... | Lifestyle(3)  | Lifestyle(3)  |
+-----------------+---------------+-----+---------------+---------------+
| age             | age(0)        | ... | age(4)        | age(4)        |
+-----------------+---------------+-----+---------------+---------------+
| cholestrol      | cholestrol(0) | ... | cholestrol(2) | cholestrol(2) |
+-----------------+---------------+-----+---------------+---------------+
| diet            | diet(0)       | ... | diet(0)       | diet(1)       |
+-----------------+---------------+-----+---------------+---------------+
| heartdisease(0) | 0.5           | ... | 0.5           | 0.5           |
+-----------------+---------------+-----+---------------+---------------+
| heartdisease(1) | 0.5           | ... | 0.5           | 0.5           |
+-----------------+---------------+-----+---------------+---------------+

In [27]:
print(model.get_cpds('age'))

+--------+----------+
| age(0) | 0.210526 |
+--------+----------+
| age(1) | 0.157895 |
+--------+----------+
| age(2) | 0.157895 |
+--------+----------+
| age(3) | 0.210526 |
+--------+----------+
| age(4) | 0.263158 |
+--------+----------+

In [29]:
print(model.get_cpds('Gender'))

+-----------+----------+
| Gender(0) | 0.526316 |
+-----------+----------+
| Gender(1) | 0.473684 |
+-----------+----------+

In [30]:
print(model.get_cpds('Family'))

+-----------+----------+
| Family(0) | 0.263158 |
+-----------+----------+
| Family(1) | 0.736842 |
+-----------+----------+